--- 
title: 'Advanced `r fontawesome::fa("r-project")` course'
subtitle: '*Tools for software development and performance*'
author: "***Robin Genuer*** [`r emoji::emoji('globe_with_meridians')`](https://robin.genuer.fr/) & ***Boris Hejblum*** [`r emoji::emoji('globe_with_meridians')`](https://borishejblum.science/)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Tools for software development and performance"
---

# Course syllabus {-}

The main goal of this course is to give you tools that ease (high-performing and effcient) code development with `r fontawesome::fa("r-project")`. The *performance* side will come as a second part, and the initial tools introduced are also very useful in situations that do not require
important computation times.

We will focus the presentation of these development tools focuusing on the notion of **package**. *You are already familiar with this notion*, as you have already
already installed packages from the CRAN for example ! You also know that it is the most standard way in `r fontawesome::fa("r-project")` to distribuute code and make it available.
We will show you that the package is also an excellent tool for developing code.


We will follow the outline below:

 1. Build a package

 2. **Tracking** changes, **sharing** code, **collaborative** development and automating tests in a package

 3. **Measure** computation time

 4. **Profile** the code

 5. Use `Rcpp` to **optimize** what needs to be optimized

 6. **Parallelize** the code easily


## Required tools

To take this course, you will need to have the following softwares installed:

  - the latest version of `r fontawesome::fa("r-project")` (https://cloud.r-project.org/)

  - the latest version of `RStudio` (https://posit.co/download/rstudio-desktop/#download)

  - a *C++ compiler* (such as `gcc` or `clang` - native on UNIX systems, 
	for Windows users we recommend installing 
	[Rtools](https://cran.r-project.org/bin/windows/Rtools/), for 
	Mac users it may be necessary to install the macOS tool chain --- namely `Xcode Command Line Tools` and `gfortran` --- used by `r fontawesome::fa("r-project")` as detailed [here](https://thecoatlessprofessor.com/software-releases/macrtools-v0.0.1-released-automatic-macos-r-compiled-toolchain-installation-from-within-r/)[^1] 
	
[^1]: updating and automating [this toolchain installation](http://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-os-x/)

  - the following `r fontawesome::fa("r-project")` packages: `devtools`, `future.apply`, `itertools`, `microbenchmark`, `mvtnorm`, `profvis`, `Rcpp`, `RcppArmadillo`, `roxygen2`, `testthat`, `usethis`

  - the software [*git*](https://git-scm.com/) which can be installed following instructions from [*Happy Git With R* by Jenny Brian](https://happygitwithr.com/install-git.html)
